pista(horizontal, 1, izquierda, 1).
pista(horizontal, 2, izquierda, 3).
pista(horizontal, 3, izquierda, 3).
pista(horizontal, 4, izquierda, 2).
pista(horizontal, 1, derecha, 3).
pista(horizontal, 2, derecha, 1).
pista(horizontal, 3, derecha, 2).
pista(horizontal, 4, derecha, 3).
pista(vertical, 1, arriba, 1).
pista(vertical, 2, arriba, 2).
pista(vertical, 3, arriba, 3).
pista(vertical, 4, arriba, 2).
pista(vertical, 1, abajo, 2).
pista(vertical, 2, abajo, 1).
pista(vertical, 3, abajo, 2).
pista(vertical, 4, abajo, 3).
